import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import walletRouter from "./wallet.js";
import racesRouter from "./races.js";
import leaderboardRouter from "./leaderboard.js";
import paymentsRouter from "./payments.js";
import walkRouter from "./walk.js";
import presenceRouter from "./presence.js";
import chatRouter from "./chat.js";
import notificationsRouter from "./notifications.js";
import realtimeRouter from "./realtime.js";
import socialRouter from "./social.js";
import profileRouter from "./profile.js";
import achievementsRouter from "./achievements.js";
import coinsRouter from "./coins.js";
import trackThemesRouter from "./trackThemes.js";
import preferencesRouter from "./preferences.js";
import entitlementsRouter from "./entitlements.js";
import reportsRouter from "./reports.js";
import spectateRouter from "./spectate.js";
import depositRouter from "./deposit.js";
import groupsRouter from "./groups.js";
import sponsoredEventsRouter from "./sponsoredEvents.js";
import coinsBattleRouter from "./coinsBattle.js";
import pushRouter from "./push.js";
import adminRouter from "./admin.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(walletRouter);
router.use(racesRouter);
router.use(leaderboardRouter);
router.use(paymentsRouter);
router.use(walkRouter);
router.use(presenceRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(realtimeRouter);
router.use(socialRouter);
router.use(achievementsRouter);
router.use(coinsRouter);
router.use(trackThemesRouter);
router.use(preferencesRouter);
router.use(entitlementsRouter);
router.use(reportsRouter);
router.use(spectateRouter);
router.use(depositRouter);
router.use(groupsRouter);
router.use(sponsoredEventsRouter);
router.use(coinsBattleRouter);
router.use(pushRouter);
router.use(adminRouter);

export default router;
