import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import walletRouter from "./wallet";
import racesRouter from "./races";
import leaderboardRouter from "./leaderboard";
import paymentsRouter from "./payments";
import walkRouter from "./walk";
import presenceRouter from "./presence";
import chatRouter from "./chat";
import notificationsRouter from "./notifications";
import realtimeRouter from "./realtime";
import socialRouter from "./social";
import profileRouter from "./profile";
import achievementsRouter from "./achievements";
import coinsRouter from "./coins";
import trackThemesRouter from "./trackThemes";
import preferencesRouter from "./preferences";
import entitlementsRouter from "./entitlements";
import reportsRouter from "./reports";
import spectateRouter from "./spectate";
import depositRouter from "./deposit";
import groupsRouter from "./groups";
import sponsoredEventsRouter from "./sponsoredEvents";
import coinsBattleRouter from "./coinsBattle";
import pushRouter from "./push";
import adminRouter from "./admin";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(profileRouter);
router.use(walletRouter);
router.use(racesRouter);
router.use(leaderboardRouter);
router.use(paymentsRouter);
router.use(walkRouter);
router.use(presenceRouter);
router.use(chatRouter);
router.use(notificationsRouter);
router.use(realtimeRouter);
router.use(socialRouter);
router.use(achievementsRouter);
router.use(coinsRouter);
router.use(trackThemesRouter);
router.use(preferencesRouter);
router.use(entitlementsRouter);
router.use(reportsRouter);
router.use(spectateRouter);
router.use(depositRouter);
router.use(groupsRouter);
router.use(sponsoredEventsRouter);
router.use(coinsBattleRouter);
router.use(pushRouter);
router.use(adminRouter);

export default router;
